# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 16:28


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20170222_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchoutput',
            name='research_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='repository.ResearchItem'),
        ),
    ]
