# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import markitup.fields


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_researchoutput_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchitem',
            name='_funders_rendered',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='researchitem',
            name='funders',
            field=markitup.fields.MarkupField(default='', no_rendered_field=True),
            preserve_default=False,
        ),
    ]
