# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import markitup.fields


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_auto_20170222_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchitem',
            name='license',
            field=models.CharField(choices=[(b'cc-by-3', b'Creative Commons Attribution 3.0 Unported License')], default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='researchitem',
            name='funders',
            field=markitup.fields.MarkupField(blank=True, no_rendered_field=True),
        ),
    ]
