# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_auto_20170222_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchitem',
            name='license',
            field=models.CharField(choices=[(b'cc-by-3.0', b'Creative Commons Attribution 3.0 Unported License')], max_length=16),
        ),
    ]
