# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 13:40


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0009_auto_20170223_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchitem',
            old_name='license',
            new_name='licence',
        ),
    ]
