# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0010_auto_20170223_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchitem',
            name='licence',
            field=models.CharField(blank=True, choices=[(b'cc-by-3.0', b'Creative Commons Attribution 3.0 Unported License')], max_length=16),
        ),
    ]
