# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 10:44


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0011_auto_20170223_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='link_behaviour',
            field=models.CharField(choices=[(b'profile-page', b'A profile page on research.mysociety.org'), (b'url', b"Directly to the person's own URL (if known)"), (b'none', b'Do not link this name')], default='none', help_text=b"How should we link this person's name when given as an author?", max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='list_as_author',
            field=models.BooleanField(default=False, help_text=b'Should this person be included in the list of authors?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='twitter',
            field=models.CharField(blank=True, help_text=b"This person's Twitter handle.", max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='url',
            field=models.CharField(blank=True, help_text=b'A URL with more information on this person (such as an institutional URL).', max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='institution',
            field=models.CharField(blank=True, help_text=b'The institution this person works for.', max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='orcid',
            field=models.CharField(blank=True, help_text=b"This person's ORCID ID (https://orcid.org/).", max_length=19, verbose_name=b'ORCID ID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='researcherid',
            field=models.CharField(blank=True, help_text=b"This person's ResearcherID (https://www.researcherid.com/).", max_length=30, verbose_name=b'ResearcherID'),
        ),
    ]
