# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0016_auto_20170324_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='googlescholar',
            field=models.CharField(blank=True, help_text=b"This person's Google Scholar ID (https://scholar.google.com/).", max_length=30, verbose_name=b'Google Scholar ID'),
        ),
    ]
