# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-26 15:14


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0017_person_googlescholar'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchitem',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text=b'The thumbnail of this research.', null=True, upload_to=b'thumbnails/'),
        ),
    ]
