# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-26 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0018_researchitem_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchitem',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text=b'The thumbnail of this research. Recommended ratio is 150x110.', null=True, upload_to=b'thumbnails/'),
        ),
    ]
