# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-05 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0020_auto_20170630_1039'),
        ('repository', '0020_researchoutput_download_count'),
    ]

    operations = [
    ]
