# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-05 14:05


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0021_merge_20170705_1109"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.SlugField(allow_unicode=True, max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name="researchitem",
            name="tags",
            field=models.ManyToManyField(to="repository.Tag"),
        ),
    ]
