# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-31 09:39


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0026_auto_20170727_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchoutput',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
