# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-24 16:42


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0027_researchoutput_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='top_bar',
            field=models.BooleanField(default=False, help_text=b'Should this category appear on the top bar?'),
        ),
    ]
