# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-24 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0028_tag_top_bar'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='label',
            field=models.SlugField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
