# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-24 16:49


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0029_tag_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='label',
            field=models.CharField(max_length=30),
        ),
    ]
