# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-24 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0030_auto_20180524_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='top_bar',
            field=models.IntegerField(default=-1, help_text=b'Should this category appear on the top bar?'),
        ),
    ]
