# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-25 08:30


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0032_researchoutput_top_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='display_items_in_years',
            field=models.BooleanField(default=True, help_text=b'On the tag page - does it display items in years?'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='label',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
