# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-13 11:19


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0034_auto_20180613_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='description',
            field=models.CharField(default=b'', max_length=255),
        ),
        migrations.AddField(
            model_name='site',
            name='twitter',
            field=models.CharField(default=b'', max_length=30),
        ),
    ]
