# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-13 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import markitup.fields


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0035_auto_20180613_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchitem',
            name='_custom_cite_rendered',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='researchitem',
            name='custom_cite',
            field=markitup.fields.MarkupField(blank=True, default=b'', no_rendered_field=True),
        ),
    ]
