# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-15 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0038_tag_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchitem',
            name='table_of_contents_cache',
            field=models.TextField(blank=b'', default=b''),
        ),
        migrations.AddField(
            model_name='researchitem',
            name='table_of_contents_url',
            field=models.URLField(blank=True, default=b''),
        ),
    ]
