# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-09 13:37


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0041_tagdisplayfilter"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchitem",
            name="show_disclaimer",
            field=models.BooleanField(default=False),
        ),
    ]
