# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-30 08:02


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0042_researchitem_show_disclaimer"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="is_project",
            field=models.BooleanField(default=False),
        ),
    ]
