# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-15 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0043_tag_is_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchitem',
            name='social_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='researchitem',
            name='social_large',
            field=models.ImageField(blank=True, help_text=b'The thumbnail of this research. Recommended ratio is 1200*630', null=True, upload_to=b'social/'),
        ),
    ]
