# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-14 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0043_tag_is_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchitem',
            name='zip_archive',
            field=models.FileField(blank=True, help_text=b'Upload a stringprint document as a zip', null=True, upload_to=b'zips/'),
        ),
    ]
