# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-19 08:11


from django.db import migrations, models
import markitup.fields


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0046_researchitem_generate_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchitem',
            name='_photo_credit_rendered',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='researchitem',
            name='photo_credit',
            field=markitup.fields.MarkupField(blank=True, default=b'', help_text=b'Photo credit for image', no_rendered_field=True),
        ),
        migrations.AlterField(
            model_name='researchitem',
            name='custom_cite',
            field=markitup.fields.MarkupField(blank=True, default=b'', help_text=b'Replaces the automatically generate citation with a manual one.', no_rendered_field=True),
        ),
        migrations.AlterField(
            model_name='researchitem',
            name='generate_thumbnail',
            field=models.CharField(blank=True, choices=[(b'B', b'Blog'), (b'R', b'Report'), (b'P', b'Policy'), (b'C', b'Consultation'), (b'M', b'Minisite')], help_text=b'Generate a thumbnail from the hero image', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='researchitem',
            name='show_disclaimer',
            field=models.BooleanField(default=False, help_text=b'Shows external author disclaimer.'),
        ),
        migrations.AlterField(
            model_name='researchitem',
            name='table_of_contents_cache',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='researchitem',
            name='table_of_contents_url',
            field=models.URLField(blank=True, default=b'', help_text=b'External .json to create TOC'),
        ),
    ]
