# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-20 08:15


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0048_auto_20190820_0905"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="social_description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
