# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-27 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0049_tag_social_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchitem',
            name='zip_archive',
            field=models.FileField(blank=True, help_text=b'Upload a stringprint document as a zip', null=True, upload_to=b'zips/'),
        ),
    ]
