# Generated by Django 3.2 on 2021-12-23 18:29

import autoslug.fields
from django.db import migrations, models
import markitup.fields
import repository.models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0051_auto_20210217_1039"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemauthor",
            name="order",
            field=models.IntegerField(
                default=0,
                help_text="Where in the list of authors should this person appear?",
                verbose_name="Order",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="googlescholar",
            field=models.CharField(
                blank=True,
                help_text="This person's Google Scholar ID (https://scholar.google.com/).",
                max_length=30,
                verbose_name="Google Scholar ID",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="institution",
            field=models.CharField(
                blank=True,
                help_text="The institution this person works for.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="link_behaviour",
            field=models.CharField(
                choices=[
                    ("profile-page", "A profile page on research.mysociety.org"),
                    ("url", "Directly to the person's own URL (if known)"),
                    ("none", "Do not link this name"),
                ],
                default="none",
                help_text="How should we link this person's name when given as an author?",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="list_in_people",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Should this person be included in the list of people?",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="orcid",
            field=models.CharField(
                blank=True,
                help_text="This person's ORCID ID (https://orcid.org/).",
                max_length=19,
                verbose_name="ORCID ID",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="researcherid",
            field=models.CharField(
                blank=True,
                help_text="This person's ResearcherID (https://www.researcherid.com/).",
                max_length=30,
                verbose_name="ResearcherID",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=True,
                help_text="Used to produce a nice page URL for this person's work.",
                populate_from=("first_name", "last_name"),
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="twitter",
            field=models.CharField(
                blank=True, help_text="This person's Twitter handle.", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="A URL with more information on this person (such as an institutional URL).",
            ),
        ),
        migrations.AlterField(
            model_name="researchitem",
            name="authors",
            field=models.ManyToManyField(
                help_text="Authors of this research item.",
                through="repository.ItemAuthor",
                to="repository.Person",
            ),
        ),
        migrations.AlterField(
            model_name="researchitem",
            name="custom_cite",
            field=markitup.fields.MarkupField(
                blank=True,
                default="",
                help_text="Replaces the automatically generate citation with a manual one.",
                no_rendered_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="researchitem",
            name="date",
            field=models.DateField(help_text="The publication date of this item."),
        ),
        migrations.AlterField(
            model_name="researchitem",
            name="featured",
            field=models.BooleanField(
                default=False, help_text="Should this item be featured on the homepage?"
            ),
        ),
        migrations.AlterField(
            model_name="researchitem",
            name="generate_thumbnail",
            field=models.CharField(
                blank=True,
                choices=[
                    ("B", "Blog"),
                    ("R", "Report"),
                    ("P", "Policy"),
                    ("C", "Consultation"),
                    ("M", "Minisite"),
                    ("S", "Series"),
                ],
                help_text="Generate a thumbnail from the hero image",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="researchitem",
            name="hero",
            field=models.ImageField(
                blank=True,
                help_text="A hero image which will be displayed on this research's page. Recommended ratio is 1024x680.",
                null=True,
                upload_to="hero/",
            ),
        ),
        migrations.AlterField(
            model_name="researchitem",
            name="licence",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cc-by-3.0", "Creative Commons Attribution 3.0 Unported License"),
                    ("pub-rights", "Publication rights only"),
                ],
                help_text="Deprecated, use 'licencing'.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="researchitem",
            name="photo_credit",
            field=markitup.fields.MarkupField(
                blank=True,
                default="",
                help_text="Photo credit for image",
                no_rendered_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="researchitem",
            name="published",
            field=models.BooleanField(
                help_text="Should this item be visible in listings, and indexable by search engines? Items will always be visible via their URL."
            ),
        ),
        migrations.AlterField(
            model_name="researchitem",
            name="show_disclaimer",
            field=models.BooleanField(
                default=False, help_text="Shows external author disclaimer."
            ),
        ),
        migrations.AlterField(
            model_name="researchitem",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=True,
                help_text="Used to produce a nice page URL for this item.",
                populate_from=("title",),
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="researchitem",
            name="social_large",
            field=models.ImageField(
                blank=True,
                help_text="The thumbnail of this research. Recommended ratio is 1200*630",
                null=True,
                upload_to="social/",
            ),
        ),
        migrations.AlterField(
            model_name="researchitem",
            name="table_of_contents_cache",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Stores retrieved json site stucture - can also be used as a markdown field for the contents list",
            ),
        ),
        migrations.AlterField(
            model_name="researchitem",
            name="table_of_contents_url",
            field=models.URLField(
                blank=True, default="", help_text="External .json to create TOC"
            ),
        ),
        migrations.AlterField(
            model_name="researchitem",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="The thumbnail of this research. Recommended ratio is 150x110.",
                null=True,
                upload_to="thumbnails/",
            ),
        ),
        migrations.AlterField(
            model_name="researchitem",
            name="zip_archive",
            field=models.FileField(
                blank=True,
                help_text="Upload a stringprint document as a zip",
                null=True,
                storage=repository.models.OverwriteStorage(),
                upload_to="zips/",
            ),
        ),
        migrations.AlterField(
            model_name="researchoutput",
            name="button_text_value",
            field=models.CharField(
                blank=True,
                help_text="Optional custom text for the button to get this output.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="researchoutput",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="If the output is a file we should host ourselves, upload it.",
                upload_to="outputs/",
            ),
        ),
        migrations.AlterField(
            model_name="researchoutput",
            name="top_order",
            field=models.IntegerField(
                default=0, help_text="Order for under image link"
            ),
        ),
        migrations.AlterField(
            model_name="researchoutput",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="If the output is hosted elsewhere (like a journal), what is the URL?",
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="description",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="site",
            name="site_title",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="site",
            name="twitter",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="tag",
            name="date",
            field=models.DateField(
                blank=True, help_text="The publication date of this tag.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="display_items_in_years",
            field=models.BooleanField(
                default=True,
                help_text="On the tag page - does it display items in years?",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="generate_thumbnail",
            field=models.CharField(
                blank=True,
                choices=[
                    ("B", "Blog"),
                    ("R", "Report"),
                    ("P", "Policy"),
                    ("C", "Consultation"),
                    ("M", "Minisite"),
                    ("S", "Series"),
                ],
                help_text="Generate a thumbnail from the hero image",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="hero",
            field=models.ImageField(
                blank=True,
                help_text="A hero image which will be displayed on this tag's page. Recommended ratio is 1024x350.",
                null=True,
                upload_to="hero/",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="is_project",
            field=models.BooleanField(
                default=False, help_text="creates the 'part of' message in all members"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=True,
                help_text="Used to produce a nice page URL for this item.",
                populate_from=("label",),
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="The thumbnail of this research. Recommended ratio is 150x110.",
                null=True,
                upload_to="thumbnails/",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="top_bar",
            field=models.IntegerField(
                default=-1, help_text="Should this category appear on the top bar?"
            ),
        ),
        migrations.AlterField(
            model_name="taggroup",
            name="hero",
            field=models.ImageField(
                blank=True,
                help_text="A hero image which will be displayed on this tag group's page. Recommended ratio is 1024x350.",
                null=True,
                upload_to="hero/",
            ),
        ),
        migrations.AlterField(
            model_name="taggroup",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=True, populate_from="name", unique=True
            ),
        ),
    ]
