# Generated by Django 3.2.16 on 2022-10-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0052_auto_20211223_1829"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="front_page_order",
            field=models.IntegerField(default=0),
        ),
    ]
