# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 20:28


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="_content_rendered",
        ),
        migrations.AlterField(
            model_name="page",
            name="content",
            field=models.TextField(),
        ),
    ]
