# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-02 16:56


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_page_show_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='nav_order',
            field=models.IntegerField(default=-1),
        ),
    ]
