# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-25 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='new_window',
            field=models.BooleanField(default=False),
        ),
    ]
