# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-30 14:45


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_auto_20180828_1808"),
    ]

    operations = [
        migrations.CreateModel(
            name="OptOut",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("experiment", models.CharField(max_length=200)),
                ("user_id", models.CharField(max_length=200)),
            ],
        ),
    ]
