name: Tests

on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: research
          POSTGRES_PASSWORD: research
          POSTGRES_DB: research
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U research"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10

    env:
      TEST_DATABASE: postgres
      REPOSITORY_DB_HOST: 127.0.0.1
      REPOSITORY_DB_PORT: 5432
      REPOSITORY_DB_USER: research
      REPOSITORY_DB_NAME: research
      REPOSITORY_DB_PASS: research

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
        with:
          python-version: "3.13"
      - run: pip install "poetry==2.2.1"
      - run: |
          script/bootstrap
          script/test
